### ISSUE TITLE
Support obtaining certificate directly from SPIFFE Workload API

### ISSUE THREAD

**Issue by strideynet** [aws/rolesanywhere-credential-helper#72]
SPIFFE x509 SVIDs are ideal for AWS Roles Anywhere. Typically, these are fetched from a local Workload API by the application that uses them, but, today with the credential-helper, you must fetch them and write them to disk before they can be provided to the credential-helper.

It would seem beneficial to me if the credential-helper could be configured to directly fetch these from the Workload API.

This behaviour could be triggered by the presence of the SPIFFE_ENDPOINT_SOCKET environment variable or using a flag e.g `--spiffe-endpoint`.

Resources:
- https://github.com/spiffe/spiffe/blob/main/standards/SPIFFE_Workload_Endpoint.md
- https://github.com/spiffe/spiffe/blob/main/standards/SPIFFE_Workload_API.md
- https://github.com/spiffe/go-spiffe

**Comment by salrashid123** [comment]
i wroteup a small client [credential provider](https://github.com/salrashid123/aws_rolesanywhere_signer) here which does the same exchange but instead of a binary, its programmatic directly.

i dont' know spiffie at all but it seems you can acquire the x509 and key and then just apply that as a crypto.singer.    

some complications woudl come up since it seems the certs/keys can get roated out by spiffie but aws woudn't know about that unless crl's are applied and updated...


the library is ofcourse unofficial and unsupported option but having it as a library does allow for more flexiblity here (though with the credential process, all languages would be supported)

**Comment by strideynet** [comment]
Having spoken to the SPIFFE SSC, it seemed reasonable for this functionality to be published as a separate tool, which will be available here: https://github.com/spiffe/aws-spiffe-workload-helper
